import { Form } from "./SharedTypes";

export const serviceForm: Form = {
  additionalWorkComments: null,
  cancelReasons: null,
  groups: [],
  steps: [
    {
      id: "bf9b2551-dabb-4812-99ba-6c0a1b5c3095",
      jobs: [
        {
          companies: null,
          conditionalJobAction: null,
          hidden: null,
          id: "a7c9e136-3a18-4449-bea0-42307214697e",
          jobTagLabels: ["INTAKE_INSPECTION"],
          name: "Confirm Vehicle Details",
          orderIdx: 0,
          renderedByQuestions: null,
          renderedByVehicleDetails: null,
          renderedByVehicleDetailsArtificial: null,
          tasks: [
            {
              baseTaskId: null,
              baseTaskTagDescription: null,
              baseTaskTagId: null,
              baseTaskTagName: null,
              categoryId: null,
              conditionalTaskAction: "SHOW_ALL",
              estimatedMinutes: 0,
              id: "6362d414-99aa-48f4-b31c-20e1a48a3eae",
              instructions:
                "Tap blue check icons to confirm values. Grey check icons require manual entry. Required fields marked by (*).",
              inventory: null,
              isStandard: true,
              name: "Confirm Vehicle Details",
              orderIdx: 0,
              questions: [
                {
                  alerts: null,
                  anomalyCheck: null,
                  answers: null,
                  children: null,
                  conditionalQuestionParentId: null,
                  defaultOption: null,
                  id: "e11ddf08-7f79-40d4-a9c1-dc688c2ed301",
                  isRequired: false,
                  isStandard: true,
                  isVerifiable: true,
                  label: "License #",
                  options: null,
                  orderIdx: 0,
                  placeholder: "Enter a valid license",
                  position: null,
                  rangeMax: null,
                  rangeMin: null,
                  renderedByMax: null,
                  renderedByMin: null,
                  renderedByOptionIds: null,
                  tagDescription: null,
                  tagIsBridgit: true,
                  tagLabel: "NEW_VEHICLE_LICENSE",
                  type: "TEXT"
                },
                {
                  alerts: null,
                  anomalyCheck: null,
                  answers: null,
                  children: null,
                  conditionalQuestionParentId: null,
                  defaultOption: null,
                  id: "407e40f2-7317-4a96-875c-3dcf3e3b908a",
                  isRequired: false,
                  isStandard: true,
                  isVerifiable: true,
                  label: "Vehicle ID",
                  options: null,
                  orderIdx: 1,
                  placeholder: "Enter a vehicle ID",
                  position: null,
                  rangeMax: null,
                  rangeMin: null,
                  renderedByMax: null,
                  renderedByMin: null,
                  renderedByOptionIds: null,
                  tagDescription: null,
                  tagIsBridgit: true,
                  tagLabel: "NEW_VEHICLE_ID",
                  type: "TEXT"
                },
                {
                  alerts: null,
                  anomalyCheck: null,
                  answers: null,
                  children: null,
                  conditionalQuestionParentId: null,
                  defaultOption: null,
                  id: "f9f916af-9866-486c-89ff-51633e9e83c2",
                  isRequired: false,
                  isStandard: true,
                  isVerifiable: true,
                  label: "Vehicle year",
                  options: null,
                  orderIdx: 2,
                  placeholder: "Select from dropdown",
                  position: null,
                  rangeMax: null,
                  rangeMin: null,
                  renderedByMax: null,
                  renderedByMin: null,
                  renderedByOptionIds: null,
                  tagDescription: null,
                  tagIsBridgit: true,
                  tagLabel: "NEW_VEHICLE_YEAR",
                  type: "SELECT_ONE_DROPDOWN_VALUE"
                },
                {
                  alerts: null,
                  anomalyCheck: null,
                  answers: null,
                  children: null,
                  conditionalQuestionParentId: null,
                  defaultOption: null,
                  id: "d2f8661e-6884-4d85-b14e-8bdacb953ab1",
                  isRequired: false,
                  isStandard: true,
                  isVerifiable: true,
                  label: "Vehicle make",
                  options: null,
                  orderIdx: 3,
                  placeholder: "Select from dropdown",
                  position: null,
                  rangeMax: null,
                  rangeMin: null,
                  renderedByMax: null,
                  renderedByMin: null,
                  renderedByOptionIds: null,
                  tagDescription: null,
                  tagIsBridgit: true,
                  tagLabel: "NEW_VEHICLE_MAKE",
                  type: "SELECT_ONE_DROPDOWN_VALUE"
                },
                {
                  alerts: null,
                  anomalyCheck: null,
                  answers: null,
                  children: null,
                  conditionalQuestionParentId: null,
                  defaultOption: null,
                  id: "225d5569-777c-4eae-96f0-7ac546e122fe",
                  isRequired: false,
                  isStandard: true,
                  isVerifiable: true,
                  label: "Vehicle model",
                  options: null,
                  orderIdx: 4,
                  placeholder: "Select from dropdown",
                  position: null,
                  rangeMax: null,
                  rangeMin: null,
                  renderedByMax: null,
                  renderedByMin: null,
                  renderedByOptionIds: null,
                  tagDescription: null,
                  tagIsBridgit: true,
                  tagLabel: "NEW_VEHICLE_MODEL",
                  type: "SELECT_ONE_DROPDOWN_VALUE"
                },
                {
                  alerts: null,
                  anomalyCheck: null,
                  answers: null,
                  children: null,
                  conditionalQuestionParentId: null,
                  defaultOption: null,
                  id: "ba870340-ad41-4c98-8bad-74ae26a9e57b",
                  isRequired: false,
                  isStandard: true,
                  isVerifiable: true,
                  label: "Vehicle color",
                  options: null,
                  orderIdx: 5,
                  placeholder: "Select from dropdown",
                  position: null,
                  rangeMax: null,
                  rangeMin: null,
                  renderedByMax: null,
                  renderedByMin: null,
                  renderedByOptionIds: null,
                  tagDescription: null,
                  tagIsBridgit: true,
                  tagLabel: "NEW_VEHICLE_COLOR",
                  type: "SELECT_ONE_DROPDOWN_VALUE"
                },
                {
                  alerts: null,
                  anomalyCheck: null,
                  answers: null,
                  children: null,
                  conditionalQuestionParentId: null,
                  defaultOption: null,
                  id: "428810e7-4ec1-4818-91b5-f77dd87c0dd2",
                  isRequired: false,
                  isStandard: true,
                  isVerifiable: true,
                  label: "Drive type",
                  options: null,
                  orderIdx: 6,
                  placeholder: "Select from dropdown",
                  position: null,
                  rangeMax: null,
                  rangeMin: null,
                  renderedByMax: null,
                  renderedByMin: null,
                  renderedByOptionIds: null,
                  tagDescription: null,
                  tagIsBridgit: true,
                  tagLabel: "NEW_VEHICLE_DRIVE_TYPE",
                  type: "SELECT_ONE_DROPDOWN_VALUE"
                },
                {
                  alerts: null,
                  anomalyCheck: null,
                  answers: null,
                  children: null,
                  conditionalQuestionParentId: null,
                  defaultOption: null,
                  id: "be18545c-f190-400e-99e8-c94a8a41e303",
                  isRequired: false,
                  isStandard: true,
                  isVerifiable: true,
                  label: "Vehicle powertrain",
                  options: null,
                  orderIdx: 7,
                  placeholder: "Select from dropdown",
                  position: null,
                  rangeMax: null,
                  rangeMin: null,
                  renderedByMax: null,
                  renderedByMin: null,
                  renderedByOptionIds: null,
                  tagDescription: null,
                  tagIsBridgit: true,
                  tagLabel: "NEW_VEHICLE_POWERTRAIN",
                  type: "SELECT_ONE_DROPDOWN_VALUE"
                },
                {
                  alerts: null,
                  anomalyCheck: null,
                  answers: null,
                  children: null,
                  conditionalQuestionParentId: null,
                  defaultOption: null,
                  id: "46c1a45c-6b83-4c19-94a6-3884bbd934bf",
                  isRequired: false,
                  isStandard: true,
                  isVerifiable: true,
                  label: "Torque",
                  options: null,
                  orderIdx: 8,
                  placeholder: "Enter torque in foot-pound (ft-lb)",
                  position: null,
                  rangeMax: null,
                  rangeMin: null,
                  renderedByMax: null,
                  renderedByMin: null,
                  renderedByOptionIds: null,
                  tagDescription: null,
                  tagIsBridgit: true,
                  tagLabel: "NEW_TIRE_TORQUE",
                  type: "NUMERIC"
                },
                {
                  alerts: null,
                  anomalyCheck: null,
                  answers: null,
                  children: null,
                  conditionalQuestionParentId: null,
                  defaultOption: null,
                  id: "df11c7e6-779e-4b7f-a3d0-c0fdd4e97cf6",
                  isRequired: false,
                  isStandard: true,
                  isVerifiable: true,
                  label: "Tire groove count",
                  options: null,
                  orderIdx: 9,
                  placeholder: "Select from dropdown",
                  position: null,
                  rangeMax: null,
                  rangeMin: null,
                  renderedByMax: null,
                  renderedByMin: null,
                  renderedByOptionIds: null,
                  tagDescription: null,
                  tagIsBridgit: true,
                  tagLabel: "NEW_TIRE_GROOVE_COUNT",
                  type: "SELECT_ONE_DROPDOWN_VALUE"
                },
                {
                  alerts: null,
                  anomalyCheck: null,
                  answers: null,
                  children: null,
                  conditionalQuestionParentId: null,
                  defaultOption: null,
                  id: "a8d6b3f1-fe62-402a-bb6a-87e30010180a",
                  isRequired: false,
                  isStandard: true,
                  isVerifiable: true,
                  label: "Tire rotational",
                  options: [
                    {
                      id: "bfe5e3d9-4922-4517-ae2b-1f7a160ff968",
                      isRequired: null,
                      label: "Yes",
                      optionTagLabels: [],
                      orderIdx: 0
                    },
                    {
                      id: "3b5e361a-e641-485d-9884-4dff73a52e49",
                      isRequired: null,
                      label: "No",
                      optionTagLabels: [],
                      orderIdx: 1
                    }
                  ],
                  orderIdx: 10,
                  placeholder: null,
                  position: null,
                  rangeMax: null,
                  rangeMin: null,
                  renderedByMax: null,
                  renderedByMin: null,
                  renderedByOptionIds: null,
                  tagDescription: null,
                  tagIsBridgit: true,
                  tagLabel: "NEW_VEHICLE_TIRE_ROTATIONAL",
                  type: "SELECT_YES_NO"
                },
                {
                  alerts: null,
                  anomalyCheck: null,
                  answers: null,
                  children: [
                    {
                      alerts: null,
                      anomalyCheck: null,
                      answers: null,
                      children: null,
                      conditionalQuestionParentId: null,
                      defaultOption: null,
                      id: "64f9bbd7-c0bf-4cf1-8654-1df1a83c7363",
                      isRequired: false,
                      isStandard: true,
                      isVerifiable: true,
                      label: "Tire pressure",
                      options: null,
                      orderIdx: 0,
                      placeholder: "Enter PSI value",
                      position: null,
                      rangeMax: null,
                      rangeMin: null,
                      renderedByMax: null,
                      renderedByMin: null,
                      renderedByOptionIds: null,
                      tagDescription: null,
                      tagIsBridgit: true,
                      tagLabel: "NEW_TIRE_PSI_FRONT",
                      type: "NUMERIC"
                    },
                    {
                      alerts: null,
                      anomalyCheck: null,
                      answers: null,
                      children: null,
                      conditionalQuestionParentId: null,
                      defaultOption: null,
                      id: "c305954d-b193-4594-a42c-39ba3da7af50",
                      isRequired: false,
                      isStandard: true,
                      isVerifiable: true,
                      label: "Tire size",
                      options: null,
                      orderIdx: 1,
                      placeholder: "Enter tire size",
                      position: null,
                      rangeMax: null,
                      rangeMin: null,
                      renderedByMax: null,
                      renderedByMin: null,
                      renderedByOptionIds: null,
                      tagDescription: null,
                      tagIsBridgit: true,
                      tagLabel: "NEW_TIRE_SIZE_FRONT",
                      type: "TEXT"
                    }
                  ],
                  conditionalQuestionParentId: null,
                  defaultOption: null,
                  id: "16cd3f4b-af44-4b2a-8ed6-ae5b73fe5d96",
                  isRequired: false,
                  isStandard: true,
                  isVerifiable: true,
                  label: "Front tire specs",
                  options: null,
                  orderIdx: 11,
                  placeholder: null,
                  position: null,
                  rangeMax: null,
                  rangeMin: null,
                  renderedByMax: null,
                  renderedByMin: null,
                  renderedByOptionIds: null,
                  tagDescription: null,
                  tagIsBridgit: true,
                  tagLabel: "LABEL",
                  type: "PARENT"
                },
                {
                  alerts: null,
                  anomalyCheck: null,
                  answers: null,
                  children: [
                    {
                      alerts: null,
                      anomalyCheck: null,
                      answers: null,
                      children: null,
                      conditionalQuestionParentId: null,
                      defaultOption: null,
                      id: "9b48307b-0825-46ea-acff-088de1abaa81",
                      isRequired: false,
                      isStandard: true,
                      isVerifiable: true,
                      label: "Tire pressure",
                      options: null,
                      orderIdx: 0,
                      placeholder: "Enter PSI value",
                      position: null,
                      rangeMax: null,
                      rangeMin: null,
                      renderedByMax: null,
                      renderedByMin: null,
                      renderedByOptionIds: null,
                      tagDescription: null,
                      tagIsBridgit: true,
                      tagLabel: "NEW_TIRE_PSI_REAR",
                      type: "NUMERIC"
                    },
                    {
                      alerts: null,
                      anomalyCheck: null,
                      answers: null,
                      children: null,
                      conditionalQuestionParentId: null,
                      defaultOption: null,
                      id: "30f72a43-4cf3-4f0b-875e-32836c70a21c",
                      isRequired: false,
                      isStandard: true,
                      isVerifiable: true,
                      label: "Tire size",
                      options: null,
                      orderIdx: 1,
                      placeholder: "Enter tire size",
                      position: null,
                      rangeMax: null,
                      rangeMin: null,
                      renderedByMax: null,
                      renderedByMin: null,
                      renderedByOptionIds: null,
                      tagDescription: null,
                      tagIsBridgit: true,
                      tagLabel: "NEW_TIRE_SIZE_REAR",
                      type: "TEXT"
                    }
                  ],
                  conditionalQuestionParentId: null,
                  defaultOption: null,
                  id: "fadabc7a-7778-41ba-a22f-aef26e90fc4c",
                  isRequired: false,
                  isStandard: true,
                  isVerifiable: true,
                  label: "Rear tire specs",
                  options: null,
                  orderIdx: 12,
                  placeholder: null,
                  position: null,
                  rangeMax: null,
                  rangeMin: null,
                  renderedByMax: null,
                  renderedByMin: null,
                  renderedByOptionIds: null,
                  tagDescription: null,
                  tagIsBridgit: true,
                  tagLabel: "LABEL",
                  type: "PARENT"
                },
                {
                  alerts: null,
                  anomalyCheck: null,
                  answers: null,
                  children: null,
                  conditionalQuestionParentId: null,
                  defaultOption: null,
                  id: "0adddb27-20a0-4b3b-95b5-3fdb2f3f2701",
                  isRequired: false,
                  isStandard: true,
                  isVerifiable: true,
                  label: "Oil specification",
                  options: null,
                  orderIdx: 13,
                  placeholder: "Enter oil specification (if applicable)",
                  position: null,
                  rangeMax: null,
                  rangeMin: null,
                  renderedByMax: null,
                  renderedByMin: null,
                  renderedByOptionIds: null,
                  tagDescription: null,
                  tagIsBridgit: true,
                  tagLabel: "NEW_VEHICLE_OIL_SPEC",
                  type: "TEXT"
                }
              ],
              renderedByDriveTypes: null,
              renderedByOptionId: null,
              renderedByQuestions: null,
              renderedByVehicleDetails: [
                {
                  companyId: null,
                  driveType: null,
                  id: "9c395ba9-761e-4fef-b06a-8889cf5909ea",
                  isRotational: null,
                  makeModelYear: null,
                  mileageMaxValue: null,
                  mileageMinValue: null,
                  tireSizes: null,
                  vehiclePowertrain: null,
                  vehicleStatuses: ["pending"]
                }
              ],
              renderedByVehicleDetailsArtificial: null,
              taskTagDescription: null,
              taskTagId: "2e387a91-8a15-4bf0-b1f7-2a8f74dd54e5",
              taskTagName: "INTAKE_INSPECTION"
            }
          ],
          type: null
        }
      ],
      metadata: null,
      name: "Confirm Vehicle Details",
      orderIdx: 0
    },
    {
      id: "65769146-3c2e-4439-a1a1-22e0457b2464",
      jobs: [
        {
          companies: null,
          conditionalJobAction: null,
          hidden: null,
          id: "722cf6ba-91a3-48cf-8d91-2affb01aa656",
          jobTagLabels: ["START_SERVICE"],
          name: "Start Service",
          orderIdx: 0,
          renderedByQuestions: null,
          renderedByVehicleDetails: null,
          renderedByVehicleDetailsArtificial: null,
          tasks: [
            {
              baseTaskId: null,
              baseTaskTagDescription: null,
              baseTaskTagId: null,
              baseTaskTagName: null,
              categoryId: null,
              conditionalTaskAction: null,
              estimatedMinutes: 0,
              id: "6e08fd24-ac93-40df-9658-0429d6c887d7",
              instructions: null,
              inventory: "",
              isStandard: true,
              name: "Start Service",
              orderIdx: 0,
              questions: [
                {
                  alerts: null,
                  anomalyCheck: null,
                  answers: null,
                  children: null,
                  conditionalQuestionParentId: null,
                  defaultOption: null,
                  id: "aabeb89c-8d3d-44ce-8a9f-68e0b5d089c4",
                  isRequired: false,
                  isStandard: true,
                  isVerifiable: null,
                  label:
                    "Please upload a picture of the vehicle’s VIN number to confirm you are at the correct vehicle",
                  options: null,
                  orderIdx: 0,
                  placeholder: "",
                  position: null,
                  rangeMax: null,
                  rangeMin: null,
                  renderedByMax: null,
                  renderedByMin: null,
                  renderedByOptionIds: null,
                  tagDescription: null,
                  tagIsBridgit: true,
                  tagLabel: "IMAGE",
                  type: "UPLOAD_SINGLE_PHOTO"
                },
                {
                  alerts: null,
                  anomalyCheck: null,
                  answers: null,
                  children: null,
                  conditionalQuestionParentId: null,
                  defaultOption: null,
                  id: "61ed4304-aaa4-40ee-ba04-c8be4eeb2f3e",
                  isRequired: false,
                  isStandard: true,
                  isVerifiable: null,
                  label:
                    "Please upload 4 images of the vehicle, taken from each corner",
                  options: null,
                  orderIdx: 1,
                  placeholder: "",
                  position: null,
                  rangeMax: null,
                  rangeMin: null,
                  renderedByMax: null,
                  renderedByMin: null,
                  renderedByOptionIds: null,
                  tagDescription: null,
                  tagIsBridgit: true,
                  tagLabel: "IMAGE",
                  type: "UPLOAD_MULTIPLE_PHOTOS"
                },
                {
                  alerts: null,
                  anomalyCheck: null,
                  answers: null,
                  children: null,
                  conditionalQuestionParentId: null,
                  defaultOption: null,
                  id: "b70a2871-3012-4db4-925e-b6b8d4f8dc1b",
                  isRequired: true,
                  isStandard: true,
                  isVerifiable: null,
                  label:
                    "Is there considerable damage on the outside of the vehicle?",
                  options: [
                    {
                      id: "b05ac174-d153-428d-976d-135877bc444e",
                      isRequired: false,
                      label: "Yes",
                      optionTagLabels: [],
                      orderIdx: 0
                    },
                    {
                      id: "a58fb276-3f65-46c6-8aa8-fe0db35eccd5",
                      isRequired: false,
                      label: "No",
                      optionTagLabels: [],
                      orderIdx: 1
                    }
                  ],
                  orderIdx: 2,
                  placeholder: "",
                  position: null,
                  rangeMax: null,
                  rangeMin: null,
                  renderedByMax: null,
                  renderedByMin: null,
                  renderedByOptionIds: null,
                  tagDescription: null,
                  tagIsBridgit: true,
                  tagLabel: "DAMAGE",
                  type: "SELECT_YES_NO"
                },
                {
                  alerts: null,
                  anomalyCheck: null,
                  answers: null,
                  children: null,
                  conditionalQuestionParentId:
                    "b70a2871-3012-4db4-925e-b6b8d4f8dc1b",
                  defaultOption: null,
                  id: "6c9dbef5-b1da-4431-95fe-47fbc84685a4",
                  isRequired: true,
                  isStandard: true,
                  isVerifiable: null,
                  label: "Please describe the damage",
                  options: null,
                  orderIdx: 3,
                  placeholder: "Please describe the damage",
                  position: null,
                  rangeMax: null,
                  rangeMin: null,
                  renderedByMax: null,
                  renderedByMin: null,
                  renderedByOptionIds: ["b05ac174-d153-428d-976d-135877bc444e"],
                  tagDescription: null,
                  tagIsBridgit: null,
                  tagLabel: null,
                  type: "TEXT"
                },
                {
                  alerts: null,
                  anomalyCheck: null,
                  answers: null,
                  children: null,
                  conditionalQuestionParentId:
                    "b70a2871-3012-4db4-925e-b6b8d4f8dc1b",
                  defaultOption: null,
                  id: "8a211280-eebe-4ab2-8c4f-72823a8d51b6",
                  isRequired: false,
                  isStandard: true,
                  isVerifiable: null,
                  label: "Please upload a photo of the damage",
                  options: null,
                  orderIdx: 4,
                  placeholder: null,
                  position: null,
                  rangeMax: null,
                  rangeMin: null,
                  renderedByMax: null,
                  renderedByMin: null,
                  renderedByOptionIds: ["b05ac174-d153-428d-976d-135877bc444e"],
                  tagDescription: null,
                  tagIsBridgit: null,
                  tagLabel: null,
                  type: "UPLOAD_MULTIPLE_PHOTOS"
                },
                {
                  alerts: null,
                  anomalyCheck: null,
                  answers: null,
                  children: null,
                  conditionalQuestionParentId: null,
                  defaultOption: null,
                  id: "dfaeff00-e6f0-41f9-aa4a-d432d4617348",
                  isRequired: true,
                  isStandard: true,
                  isVerifiable: null,
                  label: "Are you able to enter the interior of the vehicle?",
                  options: [
                    {
                      id: "c9436551-5d50-4820-939c-e4b69e333ca0",
                      isRequired: false,
                      label: "Yes",
                      optionTagLabels: [],
                      orderIdx: 0
                    },
                    {
                      id: "96944cde-5993-4f77-8224-6af7fc0c3b49",
                      isRequired: false,
                      label: "No",
                      optionTagLabels: [],
                      orderIdx: 1
                    }
                  ],
                  orderIdx: 5,
                  placeholder: "",
                  position: null,
                  rangeMax: null,
                  rangeMin: null,
                  renderedByMax: null,
                  renderedByMin: null,
                  renderedByOptionIds: null,
                  tagDescription: null,
                  tagIsBridgit: true,
                  tagLabel: "INTERIOR_ACCESS",
                  type: "SELECT_YES_NO"
                },
                {
                  alerts: null,
                  anomalyCheck: null,
                  answers: null,
                  children: null,
                  conditionalQuestionParentId:
                    "dfaeff00-e6f0-41f9-aa4a-d432d4617348",
                  defaultOption: null,
                  id: "821b1f17-8c24-4655-8e95-fa5e1c20a3ae",
                  isRequired: true,
                  isStandard: true,
                  isVerifiable: null,
                  label: "Select a reason why you cannot access the vehicle",
                  options: [
                    {
                      id: "a014c576-20c7-4295-857f-cc82469f4ca3",
                      isRequired: false,
                      label: "Bluetooth connectivity issues",
                      optionTagLabels: [],
                      orderIdx: 0
                    },
                    {
                      id: "e74c9322-be05-4444-8e62-d5d97b89a539",
                      isRequired: false,
                      label: "Vehicle not unlocking",
                      optionTagLabels: [],
                      orderIdx: 1
                    },
                    {
                      id: "6383ca7d-2c9e-472a-bcab-39d4f94b61fa",
                      isRequired: false,
                      label: "Dead battery",
                      optionTagLabels: [],
                      orderIdx: 2
                    },
                    {
                      id: "1d53b616-5336-4c7d-920e-214d408342c0",
                      isRequired: false,
                      label: "Other",
                      optionTagLabels: [],
                      orderIdx: 3
                    }
                  ],
                  orderIdx: 6,
                  placeholder: "Select one",
                  position: null,
                  rangeMax: null,
                  rangeMin: null,
                  renderedByMax: null,
                  renderedByMin: null,
                  renderedByOptionIds: ["96944cde-5993-4f77-8224-6af7fc0c3b49"],
                  tagDescription: null,
                  tagIsBridgit: true,
                  tagLabel: "DESCRIBE_ACCESS_ISSUE",
                  type: "SELECT_ONE_DROPDOWN"
                },
                {
                  alerts: null,
                  anomalyCheck: null,
                  answers: null,
                  children: null,
                  conditionalQuestionParentId:
                    "821b1f17-8c24-4655-8e95-fa5e1c20a3ae",
                  defaultOption: null,
                  id: "e330aad0-d7ec-4e2f-aebf-3d4fb450a6fe",
                  isRequired: true,
                  isStandard: true,
                  isVerifiable: null,
                  label: "Describe the access issue",
                  options: null,
                  orderIdx: 7,
                  placeholder:
                    "Enter detail about why you cannot access the interior of the vehicle",
                  position: null,
                  rangeMax: 1000,
                  rangeMin: null,
                  renderedByMax: null,
                  renderedByMin: null,
                  renderedByOptionIds: ["1d53b616-5336-4c7d-920e-214d408342c0"],
                  tagDescription: null,
                  tagIsBridgit: true,
                  tagLabel: "DESCRIBE_ACCESS_ISSUE",
                  type: "TEXT"
                }
              ],
              renderedByDriveTypes: null,
              renderedByOptionId: null,
              renderedByQuestions: null,
              renderedByVehicleDetails: null,
              renderedByVehicleDetailsArtificial: null,
              taskTagDescription: null,
              taskTagId: "7ae9d0ad-af63-4002-b983-4e341f59527d",
              taskTagName: "START_SERVICE"
            },
            {
              baseTaskId: null,
              baseTaskTagDescription: null,
              baseTaskTagId: null,
              baseTaskTagName: null,
              categoryId: null,
              conditionalTaskAction: null,
              estimatedMinutes: 0,
              id: "6ef24ef3-6c50-49dd-b719-d6bc08d216bd",
              instructions: null,
              inventory: "Hi-Vis and wiper fluid",
              isStandard: true,
              name: "Interior Inspection",
              orderIdx: 1,
              questions: [
                {
                  alerts: null,
                  anomalyCheck: null,
                  answers: null,
                  children: null,
                  conditionalQuestionParentId: null,
                  defaultOption: null,
                  id: "1792e146-b688-4b87-a506-3c4dc253337f",
                  isRequired: false,
                  isStandard: true,
                  isVerifiable: null,
                  label: "Vehicle mileage",
                  options: null,
                  orderIdx: 0,
                  placeholder: "Odometer reading",
                  position: null,
                  rangeMax: null,
                  rangeMin: null,
                  renderedByMax: null,
                  renderedByMin: null,
                  renderedByOptionIds: null,
                  tagDescription: null,
                  tagIsBridgit: true,
                  tagLabel: "MILEAGE",
                  type: "NUMERIC"
                },
                {
                  alerts: null,
                  anomalyCheck: null,
                  answers: null,
                  children: null,
                  conditionalQuestionParentId: null,
                  defaultOption: null,
                  id: "2dae3d6f-e9bf-4b04-b516-33ab43086795",
                  isRequired: false,
                  isStandard: true,
                  isVerifiable: null,
                  label: "Please upload a photo of the driver seat",
                  options: null,
                  orderIdx: 1,
                  placeholder: "",
                  position: null,
                  rangeMax: null,
                  rangeMin: null,
                  renderedByMax: null,
                  renderedByMin: null,
                  renderedByOptionIds: null,
                  tagDescription: null,
                  tagIsBridgit: true,
                  tagLabel: "IMAGE",
                  type: "UPLOAD_SINGLE_PHOTO"
                },
                {
                  alerts: null,
                  anomalyCheck: null,
                  answers: null,
                  children: null,
                  conditionalQuestionParentId: null,
                  defaultOption: null,
                  id: "23462deb-d806-4005-82ed-6ddccd7f5949",
                  isRequired: true,
                  isStandard: true,
                  isVerifiable: null,
                  label:
                    "Are there any significant damage and/or stains in the interior and trunk?",
                  options: [
                    {
                      id: "2729a48d-c5b8-40b4-9416-884e65c10694",
                      isRequired: false,
                      label: "Yes",
                      optionTagLabels: [],
                      orderIdx: 0
                    },
                    {
                      id: "12623a49-29a7-4af3-8683-96f23c480a89",
                      isRequired: false,
                      label: "No",
                      optionTagLabels: [],
                      orderIdx: 1
                    }
                  ],
                  orderIdx: 2,
                  placeholder: "",
                  position: null,
                  rangeMax: null,
                  rangeMin: null,
                  renderedByMax: null,
                  renderedByMin: null,
                  renderedByOptionIds: null,
                  tagDescription: null,
                  tagIsBridgit: true,
                  tagLabel: "DAMAGE",
                  type: "SELECT_YES_NO"
                },
                {
                  alerts: null,
                  anomalyCheck: null,
                  answers: null,
                  children: null,
                  conditionalQuestionParentId:
                    "23462deb-d806-4005-82ed-6ddccd7f5949",
                  defaultOption: null,
                  id: "72c89e6e-ca35-482a-9988-b20d449a2b3c",
                  isRequired: true,
                  isStandard: true,
                  isVerifiable: null,
                  label: "Please describe the damage",
                  options: null,
                  orderIdx: 3,
                  placeholder: "Please describe the damage",
                  position: null,
                  rangeMax: 255,
                  rangeMin: null,
                  renderedByMax: null,
                  renderedByMin: null,
                  renderedByOptionIds: ["2729a48d-c5b8-40b4-9416-884e65c10694"],
                  tagDescription: null,
                  tagIsBridgit: null,
                  tagLabel: null,
                  type: "TEXT"
                },
                {
                  alerts: null,
                  anomalyCheck: null,
                  answers: null,
                  children: null,
                  conditionalQuestionParentId:
                    "23462deb-d806-4005-82ed-6ddccd7f5949",
                  defaultOption: null,
                  id: "de725837-0a7d-4fdb-a36b-ea7c0b344402",
                  isRequired: false,
                  isStandard: true,
                  isVerifiable: null,
                  label: "Please upload photos of the damage",
                  options: null,
                  orderIdx: 4,
                  placeholder: null,
                  position: null,
                  rangeMax: null,
                  rangeMin: null,
                  renderedByMax: null,
                  renderedByMin: null,
                  renderedByOptionIds: ["2729a48d-c5b8-40b4-9416-884e65c10694"],
                  tagDescription: null,
                  tagIsBridgit: null,
                  tagLabel: null,
                  type: "UPLOAD_MULTIPLE_PHOTOS"
                },
                {
                  alerts: null,
                  anomalyCheck: null,
                  answers: null,
                  children: null,
                  conditionalQuestionParentId: null,
                  defaultOption: null,
                  id: "a0130448-25da-424d-89c8-094f6a12d7d6",
                  isRequired: true,
                  isStandard: true,
                  isVerifiable: null,
                  label: "Is the windshield wiper fluid full? (top off if not)",
                  options: [
                    {
                      id: "ba8da35a-414b-4d21-89f1-e85a0be2ad46",
                      isRequired: false,
                      label: "Yes",
                      optionTagLabels: [],
                      orderIdx: 0
                    },
                    {
                      id: "3ccb9f24-61b4-4855-8bed-f3eb986f607c",
                      isRequired: false,
                      label: "No",
                      optionTagLabels: [],
                      orderIdx: 1
                    }
                  ],
                  orderIdx: 5,
                  placeholder: "",
                  position: null,
                  rangeMax: null,
                  rangeMin: null,
                  renderedByMax: null,
                  renderedByMin: null,
                  renderedByOptionIds: null,
                  tagDescription: null,
                  tagIsBridgit: true,
                  tagLabel: "WINDSHIELD_WIPER_FLUID",
                  type: "SELECT_YES_NO"
                }
              ],
              renderedByDriveTypes: null,
              renderedByOptionId: "c9436551-5d50-4820-939c-e4b69e333ca0",
              renderedByQuestions: null,
              renderedByVehicleDetails: null,
              renderedByVehicleDetailsArtificial: null,
              taskTagDescription: null,
              taskTagId: "7ae9d0ad-af63-4002-b983-4e341f59527d",
              taskTagName: "START_SERVICE"
            }
          ],
          type: null
        }
      ],
      metadata: null,
      name: "Start Service",
      orderIdx: 1
    },
    {
      id: "c6c56db1-3f91-40e4-aa49-e71bcc67e4b6",
      jobs: [
        {
          companies: null,
          conditionalJobAction: "SHOW_ONE",
          hidden: null,
          id: "d7a60bc1-0abe-4e4f-a867-a3578cc93852",
          jobTagLabels: [null],
          name: "JDE Starter Sample Job",
          orderIdx: 0,
          renderedByQuestions: null,
          renderedByVehicleDetails: [
            {
              companyId: null,
              driveType: null,
              id: "5fe6d976-e517-4402-8a14-539359e26f58",
              isRotational: null,
              makeModelYear: [
                {
                  make: "Chevrolet",
                  model: "Corvette",
                  year: 2022
                }
              ],
              mileageMaxValue: null,
              mileageMinValue: null,
              tireSizes: null,
              vehiclePowertrain: null,
              vehicleStatuses: null
            }
          ],
          renderedByVehicleDetailsArtificial: null,
          tasks: [
            {
              baseTaskId: null,
              baseTaskTagDescription: null,
              baseTaskTagId: null,
              baseTaskTagName: null,
              categoryId: null,
              conditionalTaskAction: "SHOW_ALL",
              estimatedMinutes: 30,
              id: "2f91601f-83bb-473c-aba6-94c34b3667e2",
              instructions:
                "These are additional service instructions for cleaning.",
              inventory:
                "Waterless Wash, Towels, Tire Shine,  Glass Cleaner, Interior Cleaner, Air Freshener, Vacuum, Trash Bag",
              isStandard: false,
              name: "Premium Cleaning",
              orderIdx: 0,
              questions: [
                {
                  alerts: [
                    {
                      body:
                        "Premium Cleaning has NOT been completed in this vehicle.",
                      id: "3acd9e98-c4d6-4f00-8aa0-d59f0ca9f31c",
                      recipientRoles: ["GY Super Admin", "Fleet Manager"],
                      renderedByMax: null,
                      renderedByMin: null,
                      renderedByOptionIds: [
                        "7d0f39d9-17ba-4fd4-8cfb-03998ed7861a"
                      ]
                    }
                  ],
                  anomalyCheck: null,
                  answers: null,
                  children: null,
                  conditionalQuestionParentId: null,
                  defaultOption: null,
                  id: "35ece41f-d4ed-4f99-b165-5dd9bbadb9ef",
                  isRequired: false,
                  isStandard: false,
                  isVerifiable: null,
                  label: "Has the Premium Cleaning service been completed? ",
                  options: [
                    {
                      id: "8e34889c-5cc4-42b7-bf80-f5928d7da8f5",
                      isRequired: false,
                      label: "Yes",
                      optionTagLabels: [],
                      orderIdx: 0
                    },
                    {
                      id: "7d0f39d9-17ba-4fd4-8cfb-03998ed7861a",
                      isRequired: false,
                      label: "No",
                      optionTagLabels: [],
                      orderIdx: 1
                    }
                  ],
                  orderIdx: 0,
                  placeholder:
                    "Trash Removal, Waterless Wash, Glass Cleaning, Wheel Cleaning, Tire Shine, High Touchpoint Interior Wipe Down, Vacuum, Air Freshener",
                  position: null,
                  rangeMax: null,
                  rangeMin: null,
                  renderedByMax: null,
                  renderedByMin: null,
                  renderedByOptionIds: null,
                  tagDescription: null,
                  tagIsBridgit: null,
                  tagLabel: null,
                  type: "SELECT_YES_NO"
                },
                {
                  alerts: null,
                  anomalyCheck: null,
                  answers: null,
                  children: null,
                  conditionalQuestionParentId:
                    "35ece41f-d4ed-4f99-b165-5dd9bbadb9ef",
                  defaultOption: null,
                  id: "b19e7b58-10ec-4572-9f90-f662aaa6312d",
                  isRequired: false,
                  isStandard: false,
                  isVerifiable: null,
                  label:
                    "Please explain why the Premium Cleaning service wasn't completed.",
                  options: null,
                  orderIdx: 1,
                  placeholder: null,
                  position: null,
                  rangeMax: 255,
                  rangeMin: null,
                  renderedByMax: null,
                  renderedByMin: null,
                  renderedByOptionIds: ["7d0f39d9-17ba-4fd4-8cfb-03998ed7861a"],
                  tagDescription: null,
                  tagIsBridgit: null,
                  tagLabel: null,
                  type: "TEXT"
                },
                {
                  alerts: [
                    {
                      body:
                        "Vehicle requires additional cleaning service. Please review the service report for further information.",
                      id: "458111a2-3b2d-4b66-b01f-dcba316029c5",
                      recipientRoles: ["GY Super Admin", "Fleet Manager"],
                      renderedByMax: null,
                      renderedByMin: null,
                      renderedByOptionIds: [
                        "a625a03c-b7c3-4196-a0ef-366a68a61d13"
                      ]
                    }
                  ],
                  anomalyCheck: null,
                  answers: null,
                  children: null,
                  conditionalQuestionParentId: null,
                  defaultOption: null,
                  id: "5972a7cf-203a-45c8-bcd9-b830fe0bacb6",
                  isRequired: false,
                  isStandard: false,
                  isVerifiable: null,
                  label:
                    "Does this vehicle require additional cleaning that isn't included in the Premium Cleaning service?",
                  options: [
                    {
                      id: "a625a03c-b7c3-4196-a0ef-366a68a61d13",
                      isRequired: false,
                      label: "Yes",
                      optionTagLabels: [],
                      orderIdx: 0
                    },
                    {
                      id: "c214d422-b9d9-46a4-83b3-285605912358",
                      isRequired: false,
                      label: "No",
                      optionTagLabels: [],
                      orderIdx: 1
                    }
                  ],
                  orderIdx: 2,
                  placeholder:
                    "Examples: Hard to Remove Stains, Sticky Residue, Foul Odors, Vomit, Heavy Spills, Pet Hair, etc.",
                  position: null,
                  rangeMax: null,
                  rangeMin: null,
                  renderedByMax: null,
                  renderedByMin: null,
                  renderedByOptionIds: null,
                  tagDescription: null,
                  tagIsBridgit: null,
                  tagLabel: null,
                  type: "SELECT_YES_NO"
                },
                {
                  alerts: null,
                  anomalyCheck: null,
                  answers: null,
                  children: null,
                  conditionalQuestionParentId:
                    "5972a7cf-203a-45c8-bcd9-b830fe0bacb6",
                  defaultOption: null,
                  id: "1cd0032f-220f-483e-9a37-fba44b602e30",
                  isRequired: false,
                  isStandard: false,
                  isVerifiable: null,
                  label:
                    "Please clearly explain any additional work found to be needed.",
                  options: null,
                  orderIdx: 3,
                  placeholder: null,
                  position: null,
                  rangeMax: 255,
                  rangeMin: null,
                  renderedByMax: null,
                  renderedByMin: null,
                  renderedByOptionIds: ["a625a03c-b7c3-4196-a0ef-366a68a61d13"],
                  tagDescription: null,
                  tagIsBridgit: null,
                  tagLabel: null,
                  type: "TEXT"
                },
                {
                  alerts: null,
                  anomalyCheck: null,
                  answers: null,
                  children: null,
                  conditionalQuestionParentId:
                    "5972a7cf-203a-45c8-bcd9-b830fe0bacb6",
                  defaultOption: null,
                  id: "c75b5cfb-2f3f-4df2-b7c4-4d7fd9a5518e",
                  isRequired: false,
                  isStandard: false,
                  isVerifiable: null,
                  label:
                    "Please upload pictures of additional work that's needed.",
                  options: null,
                  orderIdx: 4,
                  placeholder: null,
                  position: null,
                  rangeMax: null,
                  rangeMin: null,
                  renderedByMax: null,
                  renderedByMin: null,
                  renderedByOptionIds: ["a625a03c-b7c3-4196-a0ef-366a68a61d13"],
                  tagDescription: null,
                  tagIsBridgit: null,
                  tagLabel: null,
                  type: "UPLOAD_MULTIPLE_PHOTOS"
                },
                {
                  alerts: null,
                  anomalyCheck: null,
                  answers: null,
                  children: null,
                  conditionalQuestionParentId: null,
                  defaultOption: null,
                  id: "739e38a1-b524-4221-be1d-6cdd8a1bec1e",
                  isRequired: false,
                  isStandard: false,
                  isVerifiable: null,
                  label: "Post-Service Pictures",
                  options: null,
                  orderIdx: 5,
                  placeholder:
                    "Required Vehicle Photos: Exterior Front, Exterior Back, Exterior Left Side, Exterior Right Side, Interior Front, Interior Back, Interior Trunk.",
                  position: null,
                  rangeMax: null,
                  rangeMin: null,
                  renderedByMax: null,
                  renderedByMin: null,
                  renderedByOptionIds: null,
                  tagDescription: null,
                  tagIsBridgit: null,
                  tagLabel: null,
                  type: "UPLOAD_MULTIPLE_PHOTOS"
                }
              ],
              renderedByDriveTypes: null,
              renderedByOptionId: null,
              renderedByQuestions: [
                {
                  alerts: null,
                  anomalyCheck: null,
                  answers: null,
                  children: null,
                  conditionalQuestionParentId: null,
                  conditionalTaskQuestionId: null,
                  defaultOption: null,
                  id: "3bd124bb-45ef-4a45-a55e-0aa0de7c799e",
                  isRequired: false,
                  isStandard: false,
                  isVerifiable: null,
                  label: "Are you ready to start cleaning?",
                  options: [
                    {
                      id: "b01772e9-8a15-4b47-b6ad-94e262c632dd",
                      isRequired: false,
                      label: "Yes",
                      optionTagLabels: [],
                      orderIdx: 0
                    },
                    {
                      id: "6d88117f-116b-4842-a68e-5c3d4aa2410e",
                      isRequired: false,
                      label: "No",
                      optionTagLabels: [],
                      orderIdx: 1
                    }
                  ],
                  orderIdx: 0,
                  placeholder: null,
                  position: null,
                  rangeMax: null,
                  rangeMin: null,
                  renderedByMax: null,
                  renderedByMin: null,
                  renderedByOptionIds: null,
                  tagDescription: null,
                  tagIsBridgit: null,
                  tagLabel: null,
                  taskRenderedByMax: null,
                  taskRenderedByMin: null,
                  taskRenderedByOptionIds: [
                    "b01772e9-8a15-4b47-b6ad-94e262c632dd"
                  ],
                  type: "SELECT_YES_NO"
                }
              ],
              renderedByVehicleDetails: null,
              renderedByVehicleDetailsArtificial: null,
              taskTagDescription: null,
              taskTagId: null,
              taskTagName: null
            }
          ],
          type: null
        }
      ],
      metadata: null,
      name: "JDE Starter Sample Job",
      orderIdx: 2
    },
    {
      id: "786c00a2-3130-4247-9ac3-e05b8b6b9acd",
      jobs: [
        {
          companies: null,
          conditionalJobAction: null,
          hidden: null,
          id: "459d6bb1-1896-4d3b-893f-4af42728f618",
          jobTagLabels: [null],
          name: "Additional Job",
          orderIdx: 0,
          renderedByQuestions: null,
          renderedByVehicleDetails: null,
          renderedByVehicleDetailsArtificial: null,
          tasks: [
            {
              baseTaskId: null,
              baseTaskTagDescription: null,
              baseTaskTagId: null,
              baseTaskTagName: null,
              categoryId: null,
              conditionalTaskAction: null,
              estimatedMinutes: 0,
              id: "e831d01e-8232-43b1-b160-0537fa723190",
              instructions: null,
              inventory: "",
              isStandard: true,
              name: "Additional Job",
              orderIdx: 0,
              questions: [
                {
                  alerts: null,
                  anomalyCheck: null,
                  answers: null,
                  children: null,
                  conditionalQuestionParentId: null,
                  defaultOption: null,
                  id: "6a4f0096-8656-481c-ac78-b18712b074a6",
                  isRequired: true,
                  isStandard: false,
                  isVerifiable: null,
                  label: "Additional job needed",
                  options: [
                    {
                      id: "1f38dd2c-d98e-42f6-a89a-f481d0a2223a",
                      isRequired: false,
                      label: "Yes",
                      optionTagLabels: [],
                      orderIdx: 0
                    },
                    {
                      id: "ec3f9716-3115-494b-b795-edaaab1cbd9c",
                      isRequired: false,
                      label: "No",
                      optionTagLabels: [],
                      orderIdx: 1
                    }
                  ],
                  orderIdx: 0,
                  placeholder: "Do you see further issues?",
                  position: null,
                  rangeMax: null,
                  rangeMin: null,
                  renderedByMax: null,
                  renderedByMin: null,
                  renderedByOptionIds: null,
                  tagDescription: null,
                  tagIsBridgit: true,
                  tagLabel: "ADDITIONAL_WORK",
                  type: "SELECT_YES_NO"
                },
                {
                  alerts: null,
                  anomalyCheck: null,
                  answers: null,
                  children: null,
                  conditionalQuestionParentId:
                    "6a4f0096-8656-481c-ac78-b18712b074a6",
                  defaultOption: null,
                  id: "bb65f216-96c7-4c4b-a0d4-6dd3bc69bb49",
                  isRequired: true,
                  isStandard: false,
                  isVerifiable: null,
                  label: "Additional job",
                  options: [
                    {
                      id: "afcdd82e-dcda-4072-a1f1-c7589bea82b3",
                      isRequired: false,
                      label: "Four Tire Replacement",
                      optionTagLabels: [],
                      orderIdx: 0
                    },
                    {
                      id: "6cd425b9-eaae-4d10-a302-85ab03810568",
                      isRequired: false,
                      label: "Front Tire Replacement",
                      optionTagLabels: [],
                      orderIdx: 1
                    },
                    {
                      id: "4ad04b8b-0cee-47e3-a91e-62d746b7f5ca",
                      isRequired: false,
                      label: "Rear Tire Replacement",
                      optionTagLabels: [],
                      orderIdx: 2
                    },
                    {
                      id: "6bf38bac-510c-4106-9e75-0ea31c48bdbc",
                      isRequired: false,
                      label: "Four Tire Rotation",
                      optionTagLabels: [],
                      orderIdx: 3
                    },
                    {
                      id: "fcadcff3-d113-481b-86ae-ebacc4b072fb",
                      isRequired: false,
                      label: "Other - not listed",
                      optionTagLabels: [],
                      orderIdx: 4
                    }
                  ],
                  orderIdx: 1,
                  placeholder: "Please select the needed job",
                  position: null,
                  rangeMax: null,
                  rangeMin: null,
                  renderedByMax: null,
                  renderedByMin: null,
                  renderedByOptionIds: ["1f38dd2c-d98e-42f6-a89a-f481d0a2223a"],
                  tagDescription: null,
                  tagIsBridgit: true,
                  tagLabel: "ADDITIONAL_WORK_SELECTION",
                  type: "SELECT_ONE_DROPDOWN"
                }
              ],
              renderedByDriveTypes: null,
              renderedByOptionId: null,
              renderedByQuestions: null,
              renderedByVehicleDetails: null,
              renderedByVehicleDetailsArtificial: null,
              taskTagDescription: null,
              taskTagId: null,
              taskTagName: null
            }
          ],
          type: null
        }
      ],
      metadata: null,
      name: "Additional Job",
      orderIdx: 3
    }
  ],
  summary: {
    accessNotes: "",
    additionalComments: "Additional comments added when adding job to queue. ",
    cancelReason: null,
    canceledByEmail: null,
    canceledByFirstName: null,
    canceledByLastName: null,
    canceledByUserId: null,
    color: "gold",
    companyId: "8d1f3a53-9dad-487e-858e-0560de3d759d",
    companyName: "will_test",
    completedBy: null,
    dateCanceled: null,
    dateCompleted: null,
    dateCreated: "Tue, 10 May 2022 16:22:24 GMT",
    dateDeleted: null,
    dateScheduled: "Tue, 10 May 2022 16:15:00 GMT",
    driveType: "F",
    durationMinutes: 30,
    frontTirePsi: "36",
    frontTireSize: ".2",
    fuelType: null,
    grooveCount: 3,
    impact: null,
    isRotational: true,
    license: "01100011009",
    make: "Chevrolet",
    mileage: null,
    model: "Cobalt",
    oilSpecification: "Nice Oil",
    queueItemId: "f294ac05-6dc6-4f70-98ab-0eb5792dc71c",
    rearTirePsi: "36",
    rearTireSize: ".2",
    scheduledTechEmail: "will.johnston@insight.com",
    scheduledTechFirstName: "Will (Tech)",
    scheduledTechLastName: "Johnston",
    serviceId: "c9557aaa-7e14-4028-aef1-e3697b23b4b4",
    serviceIsStandard: false,
    serviceLocation: "1112 Lilley Ave, Columbus, OH 43206, USA",
    serviceLocationId: "51420dca-646d-4527-a70a-6db13a9f32d6",
    serviceName: "JDE Starter Sample Job",
    serviceTagLabel: null,
    servicedBy: "e1cb399e-5efe-4b0b-90ec-0d617f4a3a48",
    status: "SCHEDULED",
    techEmail: null,
    techFirstName: null,
    techHasSafetyGear: false,
    techHasTools: false,
    techLastName: null,
    techUserId: null,
    vehicleId: "0000010b",
    vehiclePowertrain: "electric",
    vehicleStatus: "active",
    vin: "1G1AF1F57A7192174",
    wheelTorqueFtplbs: "200",
    year: 2010
  }
};
